name: rec-env
channels:
  - default
dependencies:
  - python=3.9
  - pip:
    - Cython
    - ijson==3.1.4
    - timm==0.6.7
    - wget==3.2
    - scikit-image==0.19.3
    - "-e git+git://github.com/arielrossanigo/yaer.git#egg=yaer"
    - "-e code/"